name: Build Python

on:
  workflow_dispatch

jobs:
  checks:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Nuitka
        shell: pwsh
        run: |
          choco install -y mingw python312
          pip install nuitka --break-system-packages
          python -m nuitka --mingw64 --enable-plugin=tk-inter --onefile OutlastTogether.py

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: OutlastTogether
          path: OutlastTogether.exe
